Repository openshift-metal3/dev-scripts, pull requests merged in 2020-11, with the labels that each got.

#1139 04_setup_ironic: explicitly handle Dockerfile.ocp
  04_setup_ironic.sh
Labels: approved, lgtm

#1147 add execute permission to local-cbo.sh
  metal3-dev/local-cbo.sh
Labels: approved, lgtm

#1141 Clarify using local images in config_example.sh
  config_example.sh
Labels: approved, lgtm

#1144 Fix local-bmo script
  metal3-dev/local-bmo.sh
Labels: approved, lgtm

#1145 Remove ARG default for custom repo file in base-image
  04_setup_ironic.sh
  base-image/Dockerfile
  base-image/custom.repo
Labels: approved, lgtm

#1148 Add unit to time in "podman wait" command.
  04_setup_ironic.sh
Labels: approved, lgtm, ok-to-test

#1149 Fix local-bmo.sh script
  metal3-dev/local-bmo.sh
Labels: approved, lgtm

#1084 Fetch Pull Request to build local image
  04_setup_ironic.sh
  config_example.sh
Labels: approved, lgtm

#1155 Add GROUP variable for chown where different from USER
  02_configure_host.sh
  common.sh
  metal3-dev/local-bmo.sh
  utils.sh
Labels: approved, lgtm, ok-to-test

#1152 Additional trust bundle
  config_example.sh
  ocp_install_env.sh
Labels: approved, lgtm, ok-to-test, tide/merge-method-squash

#1151 Account for podman version < 2.0.0
  04_setup_ironic.sh
Labels: approved, lgtm

#1146 Update version detection and make dnsVIP conditional
  03_build_installer.sh
  04_setup_ironic.sh
  ocp_install_env.sh
  utils.sh
Labels: approved, lgtm

#1153 Cleanup /var/lib/libvirt/openshift-images
  ocp_cleanup.sh
Labels: approved, lgtm
