Repository openshift-metal3/dev-scripts, pull requests merged in 2020-04, with the labels that each got.

#1000 Deprecate CentOS 7
  README.md
  common.sh
Labels: CI

#991 multi-cluster: make it possible to change the docker registry image
  common.sh
  utils.sh
Labels: CI

#993 multi-cluster: pass cluster name as VM prefix
  02_configure_host.sh
  host_cleanup.sh
  vm_setup_vars.yml
Labels: CI

#1007 multi-cluster: configure registry certificate with multiple hostnames
  common.sh
  utils.sh
Labels: CI

#1005 add variable to control use of remote libvirturi in install-config
  common.sh
  ocp_install_env.sh
Labels: CI

#994 multi-cluster: compute the DNS_VIP based on the network
  common.sh
Labels: CI

#1002 Ensure same release image is used for mirror and install
  04_setup_ironic.sh
  utils.sh
Labels: CI

#1010 multi-cluster: support a log file prefix for logs that "go together"
  logging.sh
Labels: CI

#1003 multi-cluster: move messages to stderr
  common.sh
Labels: CI

#1009 multi-cluster: add script to install hive with required configuration
  README.md
  common.sh
  config_example.sh
  hive_install.sh
Labels: CI

#999 Specify v4 and v6 subnets to m3-dev-env
  vm_setup_vars.yml
Labels: CI

#939 Switch over to redfish is not running 4.3
  common.sh
Labels: CI

#1015 Align ='s with title in README.md
  README.md
Labels: approved, lgtm

#1018 base image for OpenShift CI integration
  images/Dockerfile.ci
Labels: approved, lgtm

#1021 Rename base ci image
  images/Dockerfile.ci
Labels: approved, lgtm

#1017 Add dual stack IPv4+IPv6 support
  01_install_requirements.sh
  02_configure_host.sh
  06_create_cluster.sh
  README.md
  common.sh
  config_example.sh
  ocp_cleanup.sh
  ocp_install_env.sh
  run_ci.sh
  vm_setup_vars.yml
Labels: CI, approved, lgtm

#1024 Add dummy dockerfile for CI
  images/Dockerfile.ci
Labels: approved, lgtm

#1023 Only pin metal3-dev-env when not using a local checkout
  01_install_requirements.sh
Labels: CI, approved, lgtm

#995 Install the openstack wrapper script
  01_install_requirements.sh
  02_configure_host.sh
  common.sh
Labels: CI, approved, lgtm

#1006 move the mirror log file to working dir with cluster-specific name
  04_setup_ironic.sh
  common.sh
  utils.sh
Labels: CI, approved, lgtm

#1004 multi-cluster: separate install config from cluster build
  05_create_install_config.sh
  06_create_cluster.sh
  Makefile
Labels: CI, approved, lgtm

#1026 Dockerfile file for dev-script image used by the OpenShift CI
  images/Dockerfile.ci
Labels: approved, lgtm

#1027 Fix CI image build
  images/Dockerfile.ci
Labels: approved, lgtm

#1028 Fix escape chars for CI image
  images/Dockerfile.ci
Labels: approved, lgtm
