Repository openshift-metal3/dev-scripts, pull requests merged in 2020-09, with the labels that each got.

#1086 use ROOT_DISK_NAME to set rootDeviceHints
  utils.sh
Labels: approved, lgtm

#1094 add zaneb to the owners file
  OWNERS
Labels: approved, lgtm

#1090 Install the baremetal command along with openstackclient
  02_configure_host.sh
Labels: approved, lgtm

#1095 Remove wait for ironic service
  metal3-dev/local-bmo.sh
Labels: approved, lgtm

#1093 fetch a ci token as needed for the pull secret
  .gitignore
  01_install_requirements.sh
  02_configure_host.sh
  03_build_installer.sh
  04_setup_ironic.sh
  05_create_install_config.sh
  README.md
  common.sh
  config_example.sh
  must_gather.sh
  ocp_install_env.sh
  utils.sh
Labels: approved, lgtm

#1097 Remove download of headers file when using local ipa-downloader image
  04_setup_ironic.sh
Labels: approved, lgtm, ok-to-test

#1096 Local cbo script
  metal3-dev/local-cbo.sh
Labels: approved, lgtm

#1101 assume if we are running in ci we do not need a token
  common.sh
  utils.sh
Labels: approved, lgtm

#1092 Add support to generate clouds.yaml with http_basic credentials
  clouds.yaml.template
  metal3-templater.go
  utils.sh
Labels: approved, lgtm, ok-to-test

#1100 have stop-mao.sh save the image settings
  stop-mao.sh
Labels: approved, lgtm

#1087 preserve the generated assets for debugging in case the cluster fails
  utils.sh
Labels: approved, lgtm

#1105 Fix known_hosts cleanup
  ocp_cleanup.sh
Labels: approved, lgtm

#1110 fix local registry credential handling in CI
  utils.sh
Labels: approved, lgtm

#1091 Expand dev-scripts documentation
  README.md
Labels: approved, lgtm

#1102 Empty metal3 deployment for CBO testing
  02_configure_host.sh
  assets/metal3-cbo-deployment.yaml
  utils.sh
Labels: approved, lgtm

#1113 Avoid logging auth tokens/pull secrets
  common.sh
Labels: approved, lgtm

#1103 Increase the default for MASTER_DISK too 30G
  vm_setup_vars.yml
Labels: approved, lgtm

#1111 Always include metal3-inspector 'cloud' in clouds.yaml
  clouds.yaml.template
Labels: approved, lgtm

#1107 Add PROVISIONING_NETWORK_PROFILE to config_example.sh
  config_example.sh
Labels: approved, lgtm

#1104 Switch to the Standalone ironic client
  02_configure_host.sh
  README.md
  utils.sh
Labels: approved, lgtm

#1112 metal3-dev: Fix scripts returning to MAO control
  metal3-dev/mao-bmo.sh
  metal3-dev/mao-capbm.sh
Labels: approved, lgtm

#1114 Add docs re NUM_EXTRA_WORKERS
  README.md
Labels: approved, lgtm

#1106 Add note about running multiple virt clusters
  README.md
Labels: approved, lgtm

#1109 remove support for PULL_SECRET variable
  common.sh
  run_ci.sh
  utils.sh
Labels: approved, lgtm

#990 Add ASSETS_EXTRA_FOLDER for additional manifests
  README.md
  config_example.sh
  utils.sh
Labels: CI, approved, lgtm

#1071 Add timestamps to dev-scripts logs
  logging.sh
Labels: approved, lgtm

#1119 Move assets cp before IGNITION_EXTRA
  utils.sh
Labels: approved, lgtm
