Repository openshift-metal3/dev-scripts, pull requests merged in 2021-01, with the labels that each got.

#1175 change CI registry hostname
  common.sh
  config_example.sh
  docs/custom-mao-and-capbm.md
  docs/release-payload.md
  images/Dockerfile.ci
  utils.sh
  validation.sh
Labels: approved, lgtm

#1177 Add nss_wrapper to Dockerfile.ci
  images/Dockerfile.ci
Labels: approved, lgtm, ok-to-test

#1140 Extract code to build base-image for custom images
  04_setup_ironic.sh
  build-base-image.sh
Labels: approved, lgtm

#1180 Add risk reduction for DNSpooq by setting cache-size=0
  05_create_install_config.sh
Labels: approved, lgtm

#1181 Fix name of ROOT_DISK_NAME in config_example.sh
  config_example.sh
Labels: approved, lgtm, ¯\_(ツ)_/¯
