Repository openshift-metal3/dev-scripts, pull requests merged in 2023-12, with the labels that each got.

#1616 Revert "METAL-759: Add nfs a backed persistent volume (#1608)"
  01_install_requirements.sh
  02_configure_host.sh
  06_create_cluster.sh
  common.sh
  config_example.sh
  host_cleanup.sh
Labels: approved, lgtm

#1604 AGENT-337: When using ZTP manifests, support both VIP and VIPs
  agent/roles/manifests/templates/agent-cluster-install_yaml.j2
Labels: approved, lgtm

#1611 AGENT-736: Dev-script support for generic external platform
  agent/05_agent_configure.sh
  agent/common.sh
  agent/docs/none-and-external-platform.md
  agent/roles/manifests/templates/agent-cluster-install_yaml.j2
  agent/roles/manifests/templates/install-config_yaml.j2
  agent/roles/manifests/vars/main.yml
  config_example.sh
Labels: approved, lgtm

#1614 Work around the impending openshift-sdn deprecation in the installer
  network.sh
  ocp_install_env.sh
  utils.sh
Labels: approved, lgtm

#1617 NO-ISSUE: Install packet-python in 3.11 environment
  images/Dockerfile.ci
Labels: approved, lgtm, needs-ok-to-test

#1609 Add build arg to custom release
  agent/04_agent_prepare_release.sh
  agent/docs/custom-release.md
Labels: approved, lgtm

#1618 OCPBUGS-18596: use 2 replicas when the image registry is backed by a PVC
  06_create_cluster.sh
Labels: approved, lgtm, ok-to-test

#1619 MGMT-16396: Install ansible.posix collection
  images/Dockerfile.ci
Labels: approved, lgtm, ok-to-test
